{"name": "test_get_customer_info_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create customer token: {\"message\":\"The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.\"}\nassert 401 == 200\n +  where 401 = <Response [401]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x000001B0D5EC8320>\n\n    @pytest.fixture\n    def customer_token(self):\n        url = f\"{self.base_url}/integration/customer/token/\"\n        response = ApiRequests.post(url, json=self.token_payload, headers=self.common_headers)\n>       assert response.status_code == 200, f\"Failed to create customer token: {response.text}\"\nE       AssertionError: Failed to create customer token: {\"message\":\"The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.\"}\nE       assert 401 == 200\nE        +  where 401 = <Response [401]>.status_code\n\napi_test.py:71: AssertionError"}, "description": "Test get customer info with wrong credentials", "start": 1708894979511, "stop": 1708894979511, "uuid": "587ffc43-b0e6-4f88-8241-422187f72d5d", "historyId": "b43116f1e4190a65f39884dda2463a77", "testCaseId": "b43116f1e4190a65f39884dda2463a77", "fullName": "api_test.TestApi#test_get_customer_info_with_wrong_data", "labels": [{"name": "feature", "value": "API Tests"}, {"name": "story", "value": "Customer Management"}, {"name": "tag", "value": "api"}, {"name": "tag", "value": "xdist_group(name='serial')"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "3512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}